#!/usr/bin/env python3
"""Write app/src/main/legal/python-licenses.txt: everything Python-side in the APK.

That is:
- every package Chaquopy's pip installs into the app, read from its build output
  (`app/build/python/pip/<variant>/`): name, version, declared licence, and the
  licence files each package ships in its dist-info;
- the two packages vendored into app/src/main/python (anipy_api, weeb_cli);
- the runtime underneath: CPython 3.11 under the PSF licence, Chaquopy, and the
  Android libraries (androidx.core, the Kotlin standard library).

The phone build copies the file into the app's web assets (phone/vite.config.js →
legal()), and Settings → About shows it. Gradle runs this before it
builds. It needs one Gradle build to have happened; without that it keeps the file
already there and says so.

Usage: tools/gen-licenses.py [variant]   (default: debug)
"""

import email
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PIP = ROOT / "app" / "build" / "python" / "pip"
PY_SRC = ROOT / "app" / "src" / "main" / "python"
OUT = ROOT / "app" / "src" / "main" / "legal" / "python-licenses.txt"
PSF = Path("/usr/lib") / f"python3.{sys.version_info.minor}" / "LICENSE.txt"
RULE = "-" * 78

LICENCE_FILE = ("licen", "copying", "notice", "authors")

# The runtime the packages run on — not pip packages, so declared here.
RUNTIME = [
    ("CPython", "3.11 (Chaquopy build)", "PSF-2.0", "https://www.python.org/",
     "Python Software Foundation License Version 2 — text below."),
    ("Chaquopy", "15.0.1", "MIT", "https://github.com/chaquo/chaquopy",
     "Copyright (c) Chaquo Ltd. Chaquopy is the Python SDK the app is built with."),
    ("androidx.core:core-ktx", "1.13.1", "Apache-2.0", "https://developer.android.com/jetpack/androidx",
     "Copyright The Android Open Source Project. "
     "Licensed under the Apache License, Version 2.0: https://www.apache.org/licenses/LICENSE-2.0"),
    ("Kotlin standard library", "1.9.22", "Apache-2.0", "https://kotlinlang.org/",
     "Copyright JetBrains s.r.o. and Kotlin Programming Language contributors. "
     "Licensed under the Apache License, Version 2.0: https://www.apache.org/licenses/LICENSE-2.0"),
]


def _licence_of(meta):
    if meta.get("License-Expression"):
        return meta["License-Expression"]
    lic = (meta.get("License") or "").strip()
    if lic and len(lic) < 60 and "\n" not in lic:
        return lic
    classes = [c.split("::")[-1].strip() for c in meta.get_all("Classifier") or [] if c.startswith("License ::")]
    if classes:
        return " / ".join(classes)
    return lic.splitlines()[0][:60] if lic else "UNKNOWN"


def _texts(dist):
    out = []
    for p in sorted(dist.rglob("*")):
        if p.is_file() and p.name.lower().startswith(LICENCE_FILE):
            out.append(p.read_text(errors="replace").strip())
    return out


def pip_packages(variant):
    found = {}
    base = PIP / variant
    for dist in sorted(base.glob("*/*.dist-info")):
        meta = email.message_from_string((dist / "METADATA").read_text(errors="replace"))
        name, version = meta.get("Name"), meta.get("Version")
        key = (name or dist.name).lower()
        if key in found:
            continue
        found[key] = {
            "name": name, "version": version, "licence": _licence_of(meta),
            "source": meta.get("Home-page") or next(
                (u.split(",", 1)[1].strip() for u in meta.get_all("Project-URL") or []
                 if u.lower().startswith(("source", "repository", "homepage", "home"))), ""),
            "texts": _texts(dist),
        }
    return sorted(found.values(), key=lambda d: d["name"].lower())


def vendored():
    out = []
    for pkg, name, version, licence, source in (
        ("anipy_api", "anipy-api", "3.8.21", "GPL-3.0", "https://github.com/sdaqo/anipy-cli"),
        ("weeb_cli", "weeb-cli", "3.0.0", "GPL-3.0-only", "https://github.com/ewgsta/weeb-cli"),
    ):
        d = PY_SRC / pkg
        texts = [(d / f).read_text().strip() for f in ("NOTICE", "LICENSE") if (d / f).is_file()]
        out.append({"name": f"{name} (vendored in app/src/main/python/{pkg})", "version": version,
                    "licence": licence, "source": source, "texts": texts})
    return out


def main():
    variant = sys.argv[1] if len(sys.argv) > 1 else "debug"
    if not (PIP / variant).is_dir():
        print(f"gen-licenses: no Chaquopy build output at {PIP / variant} yet — keeping {OUT.name} as it is."
              " Build once (./gradlew :app:assembleDebug), then run this again.")
        return 0
    pkgs = pip_packages(variant)
    vend = vendored()
    lines = [
        "Python packages and runtime inside Tubcal for Android",
        "",
        "Generated by tools/gen-licenses.py from the packages Chaquopy installs into the",
        "app, plus the vendored packages and the runtime underneath. Each keeps its own",
        "licence, reproduced below as it ships.",
        "",
        "Runtime:",
        *[f"  {n} {v} ({lic})" for n, v, lic, _, _ in RUNTIME],
        "Vendored:",
        *[f"  {d['name']} {d['version']} ({d['licence']})" for d in vend],
        f"Installed by pip ({len(pkgs)}):",
        *[f"  {d['name']} {d['version']} ({d['licence']})" for d in pkgs],
        "",
    ]
    for n, v, lic, src, note in RUNTIME:
        lines += [RULE, f"{n} {v}", f"Licence: {lic}", f"Source: {src}", "", note, ""]
        if n == "CPython" and PSF.is_file():
            lines += [PSF.read_text().strip(), ""]
    for d in vend + pkgs:
        lines += [RULE, f"{d['name']} {d['version']}", f"Licence: {d['licence']}"]
        if d["source"]:
            lines.append(f"Source: {d['source']}")
        lines += ["", "\n\n".join(d["texts"]) if d["texts"] else
                  "(no licence file shipped with this package; its metadata declares the licence above)", ""]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    print(f"gen-licenses: {len(pkgs)} pip packages + {len(vend)} vendored + runtime → {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
